site_name: Réseau LoRaWAN Tetaneutral.net
site_url: https://docs.lora.tetaneutral.net
site_author: Tetaneutral.net
site_description: Documentation LoRaWAN Toulouse
copyright: Copyright © 2020 Tetaneutral.net

docs_dir: 'docs'

theme:
  name: 'material'
  language: fr
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  include_sidebar: true
  palette:
    primary: indigo
    accent: indigo
  features:
    - tabs

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - 'Le projet':
    - index.md
    - lorawan/lorawan.md
    - lorawan/crypto.md
    - faq.md
  - 'Services':
    - services/services.md
  - 'Noeuds':
    - 'Yah': devices/yah.md
    - 'esp32': devices/esp32.md
    - 'feather-m0': devices/feather-m0.md
  - 'Passerelles':
    - gateways/imst.md
    - gateways/chisterapi.md
  - 'Infrastructure réseau':
    - infra/infra.md
  - 'Tutoriels':
    - tutorials/lorawan-connection.md
    - tutorials/capteur-temperature.md
    - tutorials/noeud-mobile-et-gps.md
    - tutorials/downlink.md
    - tutorials/nodered-mqtt.md
    - tutorials/client-mqtt-python.md
