site_name: Réseau LoRaWAN Tetaneutral.net
site_url: https://docs.lora.tetaneutral.net
site_author: Tetaneutral.net
site_description: Documentation LoRaWAN Toulouse
copyright: Copyright © 2020 Tetaneutral.net

repo_name: tetaneutral.net/docs_lora
repo_url: https://github.com/NICOLASGON/docs_lora_tetaneutral

docs_dir: 'docs'

theme:
  name: 'material'
  language: fr
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  include_sidebar: true
  palette:
    primary: indigo
    accent: indigo
  features:
    - tabs

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - 'Le projet':
    - index.md
    - faq.md
    - faq_technique.md
  - 'LoRaWAN':
    - lorawan/lorawan.md
    - lorawan/crypto.md
  - 'Noeuds':
    - devices/yah.md
    - devices/esp32.md
    - devices/heltec-esp32-lora-v2.md
    - devices/feather-m0.md 
  - 'Passerelles':
    - gateways/imst.md
    - gateways/chisterapi.md
  - 'Installations':
    - installations/v1.md
    - installations/foudre.md
  - 'Tutoriels':
    - tutorials/lorawan-connection.md
    - tutorials/capteur-temperature.md
    - tutorials/noeud-mobile-et-gps.md
    - tutorials/downlink.md
    - tutorials/nodered-mqtt.md
    - tutorials/client-mqtt-python.md
  - 'Galerie':
    - gallery/divers.md
